version: 2

build:
  os: ubuntu-22.04
  tools:
    python: miniconda-latest
  jobs:
    pre_build:
      - python docs/rtd.pre.py
    post_build:
      - cp docs/images/logo-darkmode.svg $READTHEDOCS_OUTPUT/html/_static/logo-darkmode.svg
      - cp docs/images/logo-lightmode.svg $READTHEDOCS_OUTPUT/html/_static/logo-lightmode.svg

conda:
  environment: envs/docenv-linux-cpu.yaml

sphinx:
  builder: html
  configuration: docs/conf.py