name: Inferno Testing

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-env: infernotest
        environment-file: envs/testenv-ubuntu.yaml
        python-version: 3.11
        auto-update-conda: true
        auto-activate-base: false

    - name: Run tests with pytest
      run: |
        pytest -s ./test
