name: Inferno Testing

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true

    - name: Create conda environment from config
      run: |
        conda env create -f envs/testenv-ubuntu.yaml

    - name: Activate conda testing environment
      run: |
        conda activate infernotest

    - name: Run tests with pytest
      run: |
        pytest -s ./test
