name: Inferno Testing

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: envs/testenv-ubuntu.yaml
        python-version: 3.11
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: infernotest

    - name: Conda info
      run: |
        which python
        echo $PATH
        conda info
        conda env list
        conda list
        conda list --name infernotest

    - name: Activate conda environment
      run: |
        conda activate infernotest

    - name: Run tests with pytest
      run: |
        pytest -s ./test
